# Generated by hand to localize admin labels to Russian

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsale',
            options={'verbose_name': 'Групповая продажа', 'verbose_name_plural': 'Групповые продажи'},
        ),
        migrations.AlterModelOptions(
            name='pricelevel',
            options={'verbose_name': 'Ценовой уровень', 'verbose_name_plural': 'Ценовые уровни'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
            },
        ),
        migrations.AlterField(
            model_name='groupsale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='groupsale',
            name='created_by',
            field=models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='groupsale',
            name='current_members',
            field=models.IntegerField(default=1, verbose_name='Текущее количество участников'),
        ),
        migrations.AlterField(
            model_name='groupsale',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='groupsale',
            name='shift',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='group_sales',
                to='camps.programshift',
                verbose_name='Смена',
            ),
        ),
        migrations.AlterField(
            model_name='groupsale',
            name='target_members',
            field=models.IntegerField(verbose_name='Целевое количество участников'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='shift',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='price_levels',
                to='camps.programshift',
                verbose_name='Смена',
            ),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='threshold',
            field=models.IntegerField(verbose_name='Порог участников'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='discount_percent',
            field=models.IntegerField(default=10, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=models.CASCADE, to='discounts.subscriptionplan', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
