# Generated by Django 5.2.8 on 2025-11-29 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campdocument',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='camps.camp'),
        ),
        migrations.AddField(
            model_name='program',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='camps.camp'),
        ),
        migrations.AddField(
            model_name='programshift',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='camps.program'),
        ),
    ]
