# Generated by hand to localize admin labels to Russian

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camp',
            options={'verbose_name': 'Лагерь', 'verbose_name_plural': 'Лагеря'},
        ),
        migrations.AlterModelOptions(
            name='campdocument',
            options={
                'verbose_name': 'Документ лагеря',
                'verbose_name_plural': 'Документы лагерей',
            },
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='programshift',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AlterField(
            model_name='camp',
            name='accommodation_description',
            field=models.TextField(blank=True, verbose_name='Проживание'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='age_from',
            field=models.IntegerField(default=6, verbose_name='Возраст от'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='age_to',
            field=models.IntegerField(default=17, verbose_name='Возраст до'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='food_description',
            field=models.TextField(blank=True, verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='geo_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='owner',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='camps',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Владелец',
            ),
        ),
        migrations.AlterField(
            model_name='camp',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='campdocument',
            name='camp',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='documents',
                to='camps.camp',
                verbose_name='Лагерь',
            ),
        ),
        migrations.AlterField(
            model_name='campdocument',
            name='file',
            field=models.FileField(upload_to='camp_documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='campdocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='campdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='program',
            name='camp',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='programs',
                to='camps.camp',
                verbose_name='Лагерь',
            ),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_days',
            field=models.IntegerField(verbose_name='Длительность (дни)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='max_children',
            field=models.IntegerField(default=100, verbose_name='Максимум детей'),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='programshift',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='programshift',
            name='program',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='shifts',
                to='camps.program',
                verbose_name='Программа',
            ),
        ),
        migrations.AlterField(
            model_name='programshift',
            name='seats_taken',
            field=models.IntegerField(default=0, verbose_name='Занято мест'),
        ),
        migrations.AlterField(
            model_name='programshift',
            name='seats_total',
            field=models.IntegerField(verbose_name='Всего мест'),
        ),
        migrations.AlterField(
            model_name='programshift',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
